name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ToDoList   

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 4. Instalar dependencias
      - name: Install dependencies
        run: npm ci   

      # 5. Build Angular / Ionic
      - name: Build app
        run: npm run build

      # 6. Capacitor Sync
      - name: Sync Capacitor
        run: npx cap sync android

      # 7. Build APK
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      # 8. Subir APK como artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ToDoList/android/app/build/outputs/apk/debug/app-debug.apk
